import json
import os
from collections import defaultdict
import numpy as np
from owlapy.render import DLSyntaxObjectRenderer
from sklearn.metrics.pairwise import cosine_similarity
from tqdm import tqdm

from ontolearn.lp_generator.helper_funcs import (
    construct_exemplars,
    generate_concepts_parallel,
    generate_data_description,
    get_ind_to_emb,
    sample_examples_from_clusters,
)
from ontolearn.refinement_operators import ExpressRefinement
from ontolearn.utils.static_funcs import concept_len

def get_informativity_fast(global_indices_list, local_indices, epsilon, sim_matrix, similarity_type = 'mean'):
    """
    Compute the informativity of a new concept based on the similarity between
    positive examples of the new concept and positive examples of existing concepts.
    """
    sim_per_concept = []

    for global_idx in global_indices_list:

        if len(global_idx) > 0 and len(local_indices) > 0:
            sub_matrix = sim_matrix[np.ix_(local_indices, global_idx)]

            if similarity_type == 'max':
                sub_matrix = np.max(sub_matrix, axis=1)

            sim_per_concept.append(np.mean(sub_matrix))

    if not sim_per_concept:
        sim_local_to_global_mean = 0.0
    else:
        sim_local_to_global_mean = np.mean(sim_per_concept)

    sim_local_to_global_mean = max(0.0, sim_local_to_global_mean) # Ensure similarity isn't negative (relevant for Cosine similarity)

    informativity = epsilon + (1.0 - sim_local_to_global_mean) * (1.0 - epsilon)

    return informativity


class InformativityBasedLPGenerator:
    """
    Generates a dataset of Description Logic learning problems (LPs) from a given knowledge base.
    This class utilizes an informativeness-based sampling strategy to iteratively construct a dataset.
    It employs a probabilistic approach (Softmax selection with temperature scaling) where concepts
    yielding higher informativeness scores—based on novelty compared to the existing dataset—have
    a disproportionately higher probability of selection.

    Args:
        knowledge_base (KnowledgeBase): The ontology/knowledge base to generate the dataset from.
        sample_ind_size (int, optional): Number of positive and negative examples to sample for each concept. Defaults to 100.
        max_example_percent (float, optional): Maximum percentage of total KB individuals used as examples per concept. Defaults to 0.1.
        seed (int, optional): Random seed for reproducibility. Defaults to 42.
        generate_data_description (bool, optional): Whether to log a summary description of the dataset post-generation. Defaults to True.
        save_path (str, optional): Directory path to save generated datasets and informativity scores. If None, data is not saved. Defaults to None.
        beyond_alc (bool, optional): If True, utilizes an expressive refinement operator generating concepts beyond ALC logic. Defaults to False.
        embeddings (pd.DataFrame, optional): DataFrame containing individual embeddings, indexed by the short name of the individual. Defaults to None.
        inf_threshold (float, optional): Optional threshold constraint for informativity. Defaults to None.
        max_child_length (int, optional): Maximum length of child concepts generated by the refinement operator. Defaults to 10.
        max_length (int, optional): Maximum length of the generated concepts. Defaults to 10.
        refinement_expressivity (float, optional): Expressivity limit (0.0 to 1.0) for the refinement operator. 0.0 restricts to simple concepts (atomic/conjunctions), 1.0 allows complex nested restrictions. Defaults to 0.2.
        second_level_refinement (bool, optional): Whether to perform an additional, deeper level of structural refinement. Defaults to False.
        num_sub_roots (int, optional): Number of sub-roots utilized during second-level refinement. Defaults to 50.
        epsilon (float, optional): Smoothing parameter to bound informativity scores strictly between epsilon and 1. Defaults to 0.01.
        max_data_len (int, optional): The target maximum number of learning problems to include in the generated dataset. Defaults to 1000.
        max_itter (int, optional): Maximum iterations allowed for the generation loop. Defaults to 10000.
        similarity_type (str, optional): Metric for informativity calculation ('mean' or 'max'). Defaults to 'mean'.
        temperature (float, optional): Softmax temperature for probabilistic sampling. Lower values (e.g., 0.05) strictly favor maximum informativity (greedy), while higher values (e.g., 1.0) allow broader random exploration. Defaults to 0.01.
    """
    def __init__(self, knowledge_base, sample_ind_size=100, max_example_percent=0.1, seed=42,
                 generate_data_description=True, save_path=None, beyond_alc=False, embeddings=None,
                 max_child_length=10, max_length=10, refinement_expressivity=0.2, second_level_refinement=False,
                 num_sub_roots=50, epsilon=0.01, max_data_len=1000, max_itter=10000, similarity_type='mean', temperature = 0.01):
        self.kb = knowledge_base
        self.sample_ind_size = sample_ind_size
        self.dataset = dict()
        self.root = self.kb.generator.thing
        self.curr_itter = 0
        self.concept_dict = dict()
        self.concepts = None
        self.all_individuals = set(self.kb.individuals())
        self.all_individuals_str = set(i.str for i in self.all_individuals)

        self.refinement_operator = ExpressRefinement(knowledge_base=self.kb, max_child_length=max_child_length,
                                                     sample_fillers_count=5,
                                                     downsample=True, use_inverse=beyond_alc,
                                                     use_card_restrictions=beyond_alc,
                                                     use_numeric_datatypes=beyond_alc, use_time_datatypes=beyond_alc,
                                                     use_boolean_datatype=beyond_alc,
                                                     expressivity=refinement_expressivity)

        self.max_example_percent = max_example_percent
        self.seed = seed
        self.dl_syntax_renderer = DLSyntaxObjectRenderer()
        self.generate_data_description = generate_data_description
        self.save_path = save_path
        #self.global_positive_examples = dict()
        # self.global_positive_examples_embeddings = dict()
        self.embeddings = embeddings
        #self.inform_threshold = inf_threshold
        self.informativity_scores = defaultdict(list)
        self.max_length = max_length
        self.second_level_refinement = second_level_refinement
        self.num_sub_roots = num_sub_roots
        self.epsilon = epsilon
        self.curr_data_len = 0
        self.curr_itter = 0
        self.max_data_len = max_data_len
        self.max_itter = max_itter
        self.similarity_type = similarity_type
        self.temperature = max(0.001, temperature)

    def get_concepts(self):
        self.concept_dict, self.concepts = generate_concepts_parallel(self.kb, self.root, self.refinement_operator,
                                                                      self.max_example_percent, self.max_length,
                                                                      self.num_sub_roots, self.second_level_refinement)
        # randomly shuffle the concepts

    def get_sim_lookup_for_inds(self):
        all_kb_ind_list = [
            i.str.split("/")[-1] for i in self.all_individuals
            if i.str.split("/")[-1] in self.embeddings.index
        ]
        all_kb_ind_emb = self.embeddings.loc[all_kb_ind_list].values

        self.sim_matrix = cosine_similarity(all_kb_ind_emb)

        self.id_to_idx = {name: i for i, name in enumerate(all_kb_ind_list)}

    def generate_lps(self):
        print("generating concepts using the refinement operator...")
        self.get_concepts()
        if self.similarity_type == 'mean' or self.similarity_type == 'max':
            self.get_sim_lookup_for_inds()
        self.ind_to_emb = get_ind_to_emb(self.embeddings, self.concept_dict)

        print("clustering individuals based on their embeddings...")
        self.ind_to_cluster, self.clusters_to_ind, _ = construct_exemplars(self.ind_to_emb)
        all_cluster_ids = set(self.clusters_to_ind.keys())

        print("processing concepts and sampling examples based on informativity...")

        concept_to_raw_pos_neg = dict()
        concept_to_local_idx = dict()

        for concept in self.concepts:
            raw_pos_set = set(i.str for i in self.concept_dict[concept])
            raw_neg_set = self.all_individuals_str - raw_pos_set
            pos, neg = sample_examples_from_clusters(all_cluster_ids, self.ind_to_cluster, self.clusters_to_ind,
                                                     raw_pos_set, raw_neg_set, self.sample_ind_size)
            concept_to_raw_pos_neg[concept] = (raw_pos_set, raw_neg_set, pos, neg)
            # Map indices
            concept_to_local_idx[concept] = [self.id_to_idx[ind] for ind in pos if ind in self.id_to_idx]

        pbar = tqdm(total=self.max_data_len, desc="Generating Dataset")

        global_indices_list = []

        if len(self.dataset) == 0:
            # print choosing a random concept and adding it to the dataset without calculating informativity, to have a starting point for the subsequent concepts
            print("choosing a random concept to start the dataset...")
            idx = np.random.randint(0, len(self.concepts))
            concept = self.concepts[idx]

            raw_pos_set, raw_neg_set, pos, neg = concept_to_raw_pos_neg[concept]

            self.current_positive_examples = pos
            concept_name = self.dl_syntax_renderer.render(concept.get_nnf())
            self.concepts[idx] = self.concepts[-1]
            self.concepts.pop()
            self.dataset[concept_name] = {
                'positive examples': list(pos),
                'negative examples': list(neg),
                'length': concept_len(concept)
            }
            # self.global_positive_examples[concept_name] = pos
            global_indices_list.append(concept_to_local_idx[concept])
            pbar.update(1)

        while self.curr_itter < self.max_itter and len(self.concepts) > 0:
            # calculate informativity for each concept and choose the one with the highest informativity to add to the dataset next
            informativity_scores_dict = dict()

            for concept in self.concepts:
                raw_pos_set, raw_neg_set, pos, neg = concept_to_raw_pos_neg[concept]
                self.current_positive_examples = pos

                try:
                    informativity = get_informativity_fast(global_indices_list,
                                                           concept_to_local_idx[concept],
                                                           self.epsilon,
                                                           self.sim_matrix,
                                                           self.similarity_type)
                except Exception as e:
                    print(f"Error calculating informativity for concept {self.dl_syntax_renderer.render(concept)}: {e}")
                    informativity = 0.0  # if there is an error in calculating informativity, we can consider it to be 0 to avoid adding potentially redundant LPs to the dataset
                informativity_scores_dict[concept] = informativity

            concepts_list = list(informativity_scores_dict.keys())
            raw_scores = np.array(list(informativity_scores_dict.values()))

            # Calculate probabilities
            shifted_scores = raw_scores - np.max(raw_scores)
            exp_scores = np.exp(shifted_scores / self.temperature)
            probabilities = exp_scores / np.sum(exp_scores)

            best_concept = np.random.choice(concepts_list, p=probabilities)

            idx = self.concepts.index(best_concept)
            concept = self.concepts[idx]
            raw_pos_set, raw_neg_set, pos, neg = concept_to_raw_pos_neg[concept]
            self.current_positive_examples = pos
            concept_name = self.dl_syntax_renderer.render(concept.get_nnf())
            self.concepts[idx] = self.concepts[-1]
            self.concepts.pop()
            self.dataset[concept_name] = {
                'positive examples': list(pos),
                'negative examples': list(neg),
                'length': concept_len(concept)
            }

            global_indices_list.append(concept_to_local_idx[concept])

            best_inf_score = informativity_scores_dict[best_concept]
            self.informativity_scores[concept_name].append(best_inf_score)

            pbar.update(1)
            pbar.set_postfix({"inf": f"{best_inf_score:.4f}", "remaining_concepts": len(self.concepts)})

            self.curr_data_len = len(self.dataset)
            if self.curr_data_len >= self.max_data_len:
                print(f"Reached maximum data length of {self.max_data_len}. Stopping generation.")
                break
            self.curr_itter += 1

        if self.generate_data_description:
            description = generate_data_description(self.dataset)
            print(description)
        if self.save_path is not None:
            dataset = list(self.dataset.items())
            os.makedirs(self.save_path, exist_ok=True)  # Creates dir and ignores if it exists

            save_path_lp = os.path.join(self.save_path, 'generated_lps_with_inf.json')
            save_path_inf = os.path.join(self.save_path, 'informativity_scores.json')

            with open(save_path_lp, 'w', encoding="utf-8") as f1:
                json.dump(dataset, f1, indent=4, ensure_ascii=False)
            with open(save_path_inf, 'w', encoding="utf-8") as f2:
                json.dump(self.informativity_scores, f2, indent=4, ensure_ascii=False)
