name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Install tox
      id: install-tox
      run: |
        pip install tox
        echo "tox_version=$(pip list | grep tox | tr -d ' ')" >> $GITHUB_OUTPUT
    - name: Flake8 annotations matcher
      uses: rbialon/flake8-annotations@v1
    - uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-${{ steps.install-tox.outputs.tox_version }}-lint-${{ hashFiles('environment.yml', 'tox.ini') }}
        path: .tox
    - name: Lint with flake8
      run: |
        conda install flake8
        # exit-zero treats all errors as warnings. The line length is configured in tox.ini
        tox -o -e lint -- --exit-zero --max-complexity=10 --statistics --show-source
        # stop the build if there are Python syntax errors or undefined names
        tox -o -e lint -- --count --select=E9,F63,F7,F82 --statistics >/dev/null
