name: Python package

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10.14"]
      max-parallel: 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install -e .

      - name: Download datasets
        run: |
          wget https://files.dice-research.org/projects/Ontolearn/KGs.zip
          wget https://files.dice-research.org/projects/Ontolearn/LPs.zip
          unzip KGs.zip && unzip LPs.zip

      - name: Setup sparql endpoint
        run: |
          sudo docker run --name fuseki-data -v /fuseki busybox
          sudo docker run -d --name fuseki -p 3030:3030 --volumes-from fuseki-data stain/jena-fuseki
          sudo docker run --volumes-from fuseki-data -v /KGs/Mutagenesis:/staging stain/jena-fuseki ./load.sh mutagenesis mutagenesis.owl
          curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -d "query=SELECT * WHERE {?s ?p ?o}" http://localhost:3030/mutagenesis/sparql